import Foundation

/// App Static Strings
struct AppStrings {
    static let login = "Login"
    static let loginDetails = "Add your details to login"
    static let email = "Your Email"
    static let password = "Password"
    static let forgotPassword = "Forgot your password?"
    static let loginWith = "or Login With"
    static let signupLink = "Don’t have an Account?"
    static let signUp = "Sign Up"
    static let signupSubtitle = "Add your details to sign up"
    static let name = "Name"
    static let mobile = "Mobile No"
    static let address = "Address"
    static let confirmPassword = "Confirm Password"
    static let loginLink = "Already have an Account?"
    static let loginwithFacebook = "Login with Facebook"
    static let loginwithgoogle = "Login with Google"
    static let meal = "Meal"
    static let monkey = "Monkey"
    static let foodDelivery = "FOOD DELIVERY"
    static let resetPassword = "Reset Password"
    static let resetPassNote = "Please enter your email to receive a link to  create a new password via email"
    static let send = "Send"
    static let otpTitle = "We have sent an OTP to your Mobile"
    static let otpNote = "Please check your mobile number 071*****12 continue to reset your password"
    static let next = "Next"
    static let DidntReceive = "Didn't Receive?"
    static let clickHere = "Click Here"
    static let newPassword = "New Password"
    static let confiemPassword = "Confim Password"
    static let newPasswordNote = "Please enter your email to receive a link to  create a new password via email"
    static let loginNote = "Discover the best foods from over 1,000 restaurants and fast delivery to your doorstep"
    static let createAccount = "Create an Account"
}
